name: Post Whitewater webcams & weather

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *' # 15:30pm UTC = 7:30am PST
    - cron: '0 20 * * *'  # 20:00pm UTC = 12:00am PST

jobs:
  post-webcams:
    runs-on: ubuntu-latest
    env:
      MASTODON_API: https://nelson.social/api/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: MASTODON_TOKEN=${{ secrets.WHITEWATER_MASTODON_TOKEN }} npm run post-status whitewater