name: Post Avalanche Forecast

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *' # 0:30am UTC = 16:30 PST
  
jobs:
  post:
    name: Post Avalanche Forecast
    runs-on: ubuntu-latest
    env:
      MASTODON_API: https://nelson.social/api/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: MASTODON_TOKEN=${{ secrets.AVALANCHE_MASTODON_TOKEN }} npm run post-status avalanche